version: '3'

services:
  pw2-mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: pw2-mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    expose:
      - 3306
    volumes:
      - "${MYSQL_DATA}:/var/lib/mysql"

  pw2-php:
    image: php:${PHP_VERSION}
    container_name: pw2-php
    expose:
      - 80
      - 443
    ports:
      - "${PHP_PORT}:80"
      - "${PHP_SECURE_PORT}:443"
    volumes:
      - ./app/:/var/www/html
    links:
      - pw2-mysql
    command: sh ./docker-scripts/docker-php.sh
